UART_BUSY	BIT	00h
PROG		EQU	0000h

		ORG	PROG+0000h
		SJMP	START
		;Interrupt Vector Table
		ORG	PROG+0003h
		LCALL	INT0_ISR
		RETI
		ORG	PROG+000Bh
		LCALL	T0_ISR
		RETI
		ORG	PROG+0013h
		LCALL	INT1_ISR
		RETI
		ORG	PROG+001Bh
		LCALL	T1_ISR
		RETI
		ORG	PROG+0023h
		LCALL	UART_ISR
		RETI
		;
		ORG	PROG+0030h
START:
		CLR	UART_BUSY
        	MOV     TMOD, #00100001b	; Timer1 in Mode 2, Timer0 in Mode 1
      	 	MOV     TH1, #0FDh		; Baud Rate = 9600 bps at 11.0592MHz
	      	MOV     SCON, #01010000b	; UART in Mode 1
		SETB	ES			; Enable UART Interrupt
		SETB	EA			; Enable Interrupt
		SETB	TR1			; Start Timer 1
LOOP:
		JNB	P3.2,SEND
		SJMP	LOOP
SEND:
		JNB	P3.2, $
		MOV	A,P0
		CALL	UART_PUTC
		JMP	LOOP
;
INT0_ISR:
		RET
T0_ISR:
        	RET
INT1_ISR:
		RET
T1_ISR:
		RET
UART_ISR:
        	JB      RI, RECEIVED
TRANSMITTED:
		CLR	UART_BUSY
        	CLR     TI
        	RET
RECEIVED:
		MOV	A, SBUF
		CPL	A
		MOV	P1, A
		CLR     RI
		RET
;
UART_PUTC:
		JB	UART_BUSY,UART_PUTC
		SETB	UART_BUSY
		MOV	SBUF,A
		RET

DELAY:		MOV	R5,#20	;R5*20 mS
D1:     	MOV	R6,#40
D2:    	 	MOV	R7,#249
		DJNZ	R7,$
 		DJNZ	R6,D2
  		DJNZ	R5,D1
   		RET
        	END
